#!/usr/bin/python3
"""Program to read a set of numbers from a file and get the factors"""


def get_factors(numb_to_check):
    """"find two small numbers that multiply to give a given number"""
    try:
        number = int(numb_to_check)
        for itr in range(2, number + 1):
            if number % itr == 0:
                print("{}={}*{}".format(number, number//itr, itr))
                break
    except (TypeError, ZeroDivisionError, ValueError):
        pass
    return 0


def read_from_file(file_name):
    try:
        with open(file_name) as file:
            line = file.readline()
            while line != "":
                number = int(line.split('\n')[0])
                get_factors(number)
                line = file.readline()
    except (FileNotFoundError, ValueError, TypeError):
        pass


if __name__ == "__main__":
    from sys import argv
    
    if len(argv) != 2:
        exit()
    filename = argv[1]
    read_from_file(filename)
