#!/usr/bin/python3
"""Program to read a set of numbers from a file and get the factors"""


def factorize(numb_to_check):
    """"find two small numbers that multiply to give a given number"""
    init_factor = 2

    if numb_to_check < 2:
        return

    while numb_to_check % init_factor:
        init_factor += 1
    print("{:.0f}={:.0f}*{:.0f}".format(numb_to_check, numb_to_check / init_factor, init_factor))


def read_from_file(file_name):
    try:
        with open(file_name) as file:
            line = file.readline()
            while line != "":
                number = int(line.split('\n')[0])
                factorize(number)
                line = file.readline()
    except (FileNotFoundError, ValueError, TypeError):
        pass


if __name__ == "__main__":
    from sys import argv

    if len(argv) != 2:
        exit()
    filename = argv[1]
    read_from_file(filename)
