#!/usr/bin/python3
"""Program to read a set of numbers from a file and get the factors"""


def get_factors(read_number: int):
    """"Function to find 2 numbers that when multiplied will equal
    read_number
    """
    while read_number % 2 == 0:
        return 2

    init_factor = 3

    while init_factor * init_factor <= read_number:
        if read_number % init_factor == 0:
            return init_factor
        else:
            init_factor += 2
    return 1


def read_from_file(file_name):
    try:
        with open(file_name, mode="r") as file:
            line = file.readline()
            while line != "":
                number = int(line.strip())                
                # number = int(line.split('\n')[0])
                val = get_factors(number)
                print("{}={}*{}".format(number, number//val, val))
                line = file.readline()
    except FileNotFoundError:
        pass


if __name__ == "__main__":
    from sys import argv

    if len(argv) != 2:
        exit()
    filename = argv[1]
    read_from_file(filename)
