#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""


def get_factors(numb_to_check):
    """"find two small numbers that multiply to give a given number"""
    try:
        number = int(numb_to_check)
        for itr in range(2, number + 1):
            if number % itr == 0:
                factor = number // itr
                if test_prime(factor) is True and test_prime(itr) is True:
                    print("{}={}*{}".format(number, factor, itr))
                else:
                    print("[...]")
                break
    except (TypeError, ZeroDivisionError, ValueError):
        pass
    return 0


def read_from_file(file_name):
    try:
        with open(file_name) as file:
            line = file.readline()
            number = int(line.split('\n')[0])
            get_factors(number)
    except (FileNotFoundError, ValueError, TypeError):
        pass


def test_prime(val):
    output = ''
    for x in range(2, val):
        if val % x == 0:
            return False
    return val > 1


if __name__ == "__main__":
    from sys import argv

    if len(argv) != 2:
        exit()
    filename = argv[1]
    read_from_file(filename)
